// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users_feeds.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUsersFeed = `-- name: CreateUsersFeed :one
WITH new_users_feed AS (
    INSERT INTO users_feeds (user_id, feed_id)
    VALUES ($1, $2)
    ON CONFLICT DO NOTHING
    RETURNING id, user_id, feed_id, created_at, updated_at
)
SELECT new_users_feed.id, users.name as user_name, users.id as user_id, feeds.name as feed_name, feeds.id as feed_id, feeds.url as feed_url 
FROM new_users_feed 
JOIN users ON users.id = new_users_feed.user_id
JOIN feeds ON feeds.id = new_users_feed.feed_id
`

type CreateUsersFeedParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

type CreateUsersFeedRow struct {
	ID       uuid.UUID
	UserName string
	UserID   uuid.UUID
	FeedName string
	FeedID   uuid.UUID
	FeedUrl  string
}

func (q *Queries) CreateUsersFeed(ctx context.Context, arg CreateUsersFeedParams) (CreateUsersFeedRow, error) {
	row := q.db.QueryRowContext(ctx, createUsersFeed, arg.UserID, arg.FeedID)
	var i CreateUsersFeedRow
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.UserID,
		&i.FeedName,
		&i.FeedID,
		&i.FeedUrl,
	)
	return i, err
}

const getUsersFeeds = `-- name: GetUsersFeeds :many
SELECT users_feeds.id, users.name as user_name, users.id as user_id, feeds.name as feed_name, feeds.id as feed_id, feeds.url as feed_url 
FROM users_feeds 
JOIN users ON users.id = users_feeds.user_id
JOIN feeds ON feeds.id = users_feeds.feed_id
WHERE users.id = $1
`

type GetUsersFeedsRow struct {
	ID       uuid.UUID
	UserName string
	UserID   uuid.UUID
	FeedName string
	FeedID   uuid.UUID
	FeedUrl  string
}

func (q *Queries) GetUsersFeeds(ctx context.Context, id uuid.UUID) ([]GetUsersFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsersFeeds, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersFeedsRow
	for rows.Next() {
		var i GetUsersFeedsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.UserID,
			&i.FeedName,
			&i.FeedID,
			&i.FeedUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUsersFeed = `-- name: RemoveUsersFeed :exec
DELETE FROM users_feeds WHERE user_id = $1 AND feed_id = $2
`

type RemoveUsersFeedParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) RemoveUsersFeed(ctx context.Context, arg RemoveUsersFeedParams) error {
	_, err := q.db.ExecContext(ctx, removeUsersFeed, arg.UserID, arg.FeedID)
	return err
}
